name: Module Builder Docker Image
on: [pull_request]
jobs:
  build_and_push:
    name: Test Module Builder Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
      - name: Build
        run: |
          pwd
          ls
          docker build -t module-builder-test -f build/module-builder/Dockerfile .
          docker run -v `pwd`/modules/channel-web:/botpress/modules/channel-web module-builder-test sh -c 'cd modules/channel-web && yarn && yarn build && yarn package'
          ls modules/channel-web
          echo "before"
          test ! -f modules/channel-web/channel-web.tgz
          echo "after"
          echo $?
